name: PR OATS test

on:
  push:
    branches: ["main", "release-*"]
    paths:
      - ".github/workflows/pull_request_oats_test.yml"
      - "bpf/**"
      - "cmd/**"
      - "configs/**"
      - "internal/**"
      - "pkg/**"
      - "scripts/**"
  pull_request:
    branches: ["main", "release-*"]
    paths:
      - ".github/workflows/pull_request_oats_test.yml"
      - "bpf/**"
      - "cmd/**"
      - "configs/**"
      - "internal/**"
      - "pkg/**"
      - "scripts/**"

permissions:
  contents: read

jobs:
  test-matrix:
    name: "Build oats matrix"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: build matrix
        id: build-matrix
        run: |
          echo -n "matrix=" >> $GITHUB_OUTPUT
          make oats-integration-test-matrix-json >> $GITHUB_OUTPUT

  test:
    name: ${{ matrix.basename }}
    needs: test-matrix
    permissions:
      # Required for codecov
      checks: write
      pull-requests: write
      # Required for uploading artifacts
      actions: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.test-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: "go.mod"
          cache: false

      - name: Run oats tests
        env:
          MATRIX_BASENAME: ${{ matrix.basename }}
          TESTCASE_TIMEOUT: 5m
        run: make oats-test-$MATRIX_BASENAME

      - name: Upload oats test logs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        if: always()
        with:
          name: Oats test logs - ${{ matrix.basename }}
          path: internal/test/oats/${{ matrix.basename }}/build/*

      - name: Process coverage data
        run: make itest-coverage-data

      - name: Report coverage
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: ./testoutput/itest-covdata.txt
          flags: oats-test
